name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Generate coverage report
      run: |
        cd ./src/FluentEnsure.UnitTests/
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Build and deploy package
      run: |
        cd ./src/FluentEnsure/
        dotnet publish -c=Release
        # deploy
